# Generated by Django 6.0.3 on 2026-06-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='places/')),
                ('description', models.TextField()),
                ('google_map_link', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('rating_count', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='travelmate.destination')),
            ],
        ),
    ]
