# Generated by Django 6.0.3 on 2026-06-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmate', '0002_touristplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
