# Generated by Django 6.0.3 on 2026-06-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmate', '0003_touristplace_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='location',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('price_range', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('google_map_link', models.URLField()),
                ('is_open', models.BooleanField(default=True)),
                ('closing_time', models.CharField(blank=True, max_length=20, null=True)),
                ('touristplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelmate.touristplace')),
            ],
        ),
    ]
