# Generated by Django 6.0.3 on 2026-06-13 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmate', '0004_alter_touristplace_location_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='touristplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='travelmate.touristplace'),
        ),
    ]
