# Generated by Django 6.0.3 on 2026-06-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelmate', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.TextField()),
                ('adults', models.IntegerField(default=2)),
                ('children', models.IntegerField(default=0)),
                ('available_rooms', models.IntegerField(default=1)),
                ('check_in', models.CharField(max_length=20)),
                ('check_out', models.CharField(max_length=20)),
                ('google_map_link', models.URLField()),
                ('touristplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='travelmate.touristplace')),
            ],
        ),
    ]
